### ISSUE TITLE
Saving without affecting minibuffer?

### ISSUE THREAD

**Issue by jojojames** [Vifon/focus-autosave-mode.el#3]
Is there a way for the save to not affect the minibuffer output?

Some link here http://batsov.com/articles/2012/03/08/emacs-tip-number-5-save-buffers-automatically-on-buffer-or-window-switch/

From user skrat,
"I suggest replacing (when buffer-file-name with (when (and buffer-file-name (buffer-modified-p)) to prevent the meaningless (no changes need to be saved) messages."

**Comment by vifon** [comment]
The local mode already works like that, apparently. The global version is more tricky because it uses `save-some-buffers` to save all the modified buffers and I see no way to prevent it from affecting minibuffer. I will need to reimplement a simple version of it. On the other hand, then I might be able to easily add a few features I've had planned.

I will get a round to it.

**Comment by jojojames** [comment]
Would you recommend just running something like a prog-mode-hook to enable local mode then?

**Comment by vifon** [comment]
You can always create a globalized mode based on the local one with `define-globalized-minor-mode`. Right now these global and local modes are mostly independent. Anyway, you might want to wait a bit, I'm working on this as we speak.

**Comment by vifon** [comment]
It should be working as expected now. Please check.

**Comment by jojojames** [comment]
It looks like it's working. The melpa version seems to be out of date so I cloned the repo and tested with the clone.
